sudo: required
services:
    - docker

before_install:
    - docker build -t makrandkatre/docker-react -f Dockerfile.dev .

script:
    - docker run makrandkatre/docker-react npm run test -- --coverage
    